spring.application.name=bookmyshow
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=0093

# This tells Hibernate to update your tables automatically based on your code
spring.jpa.hibernate.ddl-auto=update